server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:jeudutao;DB_CLOSE_DELAY=-1
    username: sa
    password:
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
