server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/jeudutao;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  web:
    resources:
      add-mappings: false

h2:
  tcp-server:
    enabled: true
    port: 9092

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
